wandb_version: 1

epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 32
num_heads:
  desc: null
  value: 8
num_encoders:
  desc: null
  value: 2
emb_dim:
  desc: null
  value: 128
ff_dim:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.1
max_seq_len:
  desc: null
  value: 51
vocab_size:
  desc: null
  value: 472
num_parameters:
  desc: null
  value: 1277144
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.33.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708698979.712128
    t:
      1:
      - 1
      - 11
      - 40
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 40
      - 49
      - 51
      - 55
      3:
      - 1
      - 7
      - 13
      - 16
      - 23
      4: 3.9.17
      5: 0.16.3
      6: 4.33.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: epoch
      6:
      - 2
      - 3
    - 1: batch
      6:
      - 2
      - 3
    - 1: GenoLosses/geno_train_loss
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: GenoLosses/geno_val_loss
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: AB_Losses/ab_train_loss
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: AB_Losses/ab_val_loss
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: Accuracies/val_acc
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: Losses/final_val_loss
      6:
      - 3
    - 1: Accuracies/final_val_acc
      6:
      - 3
    - 1: final_epoch
      6:
      - 3
