wandb_version: 1

epochs:
  desc: null
  value: 30
batch_size:
  desc: null
  value: 32
num_heads:
  desc: null
  value: 8
num_encoders:
  desc: null
  value: 3
emb_dim:
  desc: null
  value: 256
ff_dim:
  desc: null
  value: 256
lr:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0.1
vocab_size:
  desc: null
  value: 476
num_parameters:
  desc: null
  value: 7152092
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.33.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709214370.474675
    t:
      1:
      - 1
      - 11
      - 40
      - 49
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.17
      5: 0.16.3
      6: 4.33.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
