wandb_version: 1

epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 32
num_heads:
  desc: null
  value: 8
num_encoders:
  desc: null
  value: 12
emb_dim:
  desc: null
  value: 256
ff_dim:
  desc: null
  value: 256
lr:
  desc: null
  value: 1.0e-06
weight_decay:
  desc: null
  value: 0.1
vocab_size:
  desc: null
  value: 1213
num_parameters:
  desc: null
  value: 28252349
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710254814.909799
    t:
      1:
      - 1
      - 40
      - 55
      2:
      - 1
      - 40
      - 55
      3:
      - 1
      - 7
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: epoch
      6:
      - 2
      - 3
    - 1: batch
      6:
      - 2
      - 3
    - 1: GenoLosses/geno_train_loss
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: GenoLosses/geno_val_loss
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: AB_Losses/ab_train_loss
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: AB_Losses/ab_val_loss
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: Accuracies/val_acc
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: Losses/final_val_loss
      6:
      - 3
    - 1: Accuracies/final_val_acc
      6:
      - 3
    - 1: final_epoch
      6:
      - 3
