wandb_version: 1

epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 32
num_heads:
  desc: null
  value: 8
num_encoders:
  desc: null
  value: 2
emb_dim:
  desc: null
  value: 128
ff_dim:
  desc: null
  value: 128
lr:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0.1
max_seq_len:
  desc: null
  value: 51
vocab_size:
  desc: null
  value: 475
num_parameters:
  desc: null
  value: 1277915
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708947007.649608
    t:
      1:
      - 1
      - 40
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
